### ISSUE TITLE
I have used one of your fonts in my project.

### ISSUE THREAD

**Issue by xunker** [Lewis-Clayton/dcled_ruby#10]
I made a gem for use with the Dream Cheeky LED as well and I have used your Transpo font yaml files in my project: https://github.com/xunker/peter_pan.

I've given credit in my readme, but if there are any other notices you'd like me to add please let me know.

**Comment by Lewis-Clayton** [comment]
Hi Xunker

Interesting project I'll have a play about with it later.

Happy for you use the the fonts. The more projects using that format the better. We'll all be able to benefit from new fonts.

Regards,
Lewis

**Comment by xunker** [comment]
I know this issue was closed over a year ago, but I finally got around to adding an animated gif of what your font looks like when it's being panned on a Dream Cheeky LED sign and thought you'd like to see:

![panning_text_example](https://cloud.githubusercontent.com/assets/61712/8704977/c4e3b458-2ae3-11e5-99a4-58e5f9a97418.gif)

Thanks again for making the font!

**Comment by Lewis-Clayton** [comment]
Thanks for sharing. It looks great with the viewport panning.
