### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tiredpixel** [Lewis-Clayton/dcled_ruby#6]
Hello. :) Could you please confirm the license for the code in this repository? I couldn't seem to spot it anywhere. Peace, tiredpixel

**Comment by Lewis-Clayton** [comment]
Hi Tiredpixel,

Happy to confirm the MIT License. I'll update the readme to reflect this.

Regards,

Lewis

**Comment by Lewis-Clayton** [comment]
Hi Tiredpixel,

MIT License now in effect: https://github.com/Lewis-Clayton/dcled_ruby/commit/36386475bc4291497b8122d11c635a72090c703d

Thanks again for contributing.

Regards,
Lewis
